version: '1'
services:
  backend-prod:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
      args:
        - GIT_COMMIT_HASH
    expose:
      - 8080
    restart: on-failure
    env-file:
      - ./secrets/rhapp_env
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-prod.rule=Host(`prod.api.rhapp.lol`)"
        # For using PathPrefixes
        #- "traefik.http.middlewares.strip.stripprefix.prefixes=/prod"
        #- "traefik.http.middlewares.strip.stripprefix.forceSlash=true"
        #- "traefik.http.routers.backend.middlewares=strip@docker"
      - "traefik.http.routers.backend-prod.entrypoints=websecure"
      - "traefik.http.routers.backend-prod.tls=true"
      - "traefik.http.routers.backend-prod.tls.certresolver=myresolver"

networks:
  intranet:
    name: machine_intranet
