export const available = 'Available'
export const completed = 'Completed'
export const using = 'In Use'
export const edit = 'Edit'
export const reserved = 'Reserved'
export const uncollected = 'Uncollected'
