import React from 'react'

import { TimeBlock } from '../../store/facilityBooking/types'

import { StyledViewBooking } from './BlockStyles.styled'

type Props = {
  entry: TimeBlock
  openViewBookingModal: () => void
  setViewBookingEntryId: () => void
}

/**
 *
 * The `ViewBlock` is generated by the `ViewScheduleBlock`. Each block represents an hour of the day. \
 * If there is a booking made during that hour, it displays its details. Otherwise, it is greyed out.
 *
 * @param entry (type `number`)
 * @param openViewBookingModal: (type `function`)
 * @param setViewBookingEntryId (type `function`)
 *
 * @returns An event block that contains the component displaying the: \
 *          1: Facility \
 *          2: CCA that made the booking \
 *          3: Event name \
 *          4: Date/Time of booking
 *
 * @example
 * ```
 * // For each of the 24 `timeBlock`s in the `timeBlocks`  array, a `ViewBlock` element is generated:
 * <ViewBlock
 *  key={index}
 *  entry={entry}
 *  // if day selected is not current, scroll to defaultTimePosition
 *  openViewBookingModal={() => setIsViewBookingModalOpen(true)}
 *  setViewBookingEntryId={() => fetchBooking(entry.id)}
 * />
 * ```
 *
 * @remarks
 * <any remarks on this component type in here>
 *
 */

const ViewBlock = (props: Props) => {
  return props.entry.booking ? (
    <StyledViewBooking
      isOccupied
      blockId={props.entry.id}
      onClick={() => {
        props.openViewBookingModal()
        props.setViewBookingEntryId()
      }}
    >
      {props.entry.ccaName}
      <br />
      {props.entry.eventName}
    </StyledViewBooking>
  ) : (
    <StyledViewBooking isOccupied={false} blockId={props.entry.id} />
  )
}

export default ViewBlock
