FROM python:3.8.16-bullseye

RUN apt-get update

WORKDIR /home/backend

ARG GIT_COMMIT_HASH
ENV GIT_COMMIT_HASH $GIT_COMMIT_HASH

## TODO: Split COPY statement for better caching
COPY ./backend .

RUN pip3 install -r ./requirements.txt

CMD python ./main.py > /home/output.txt 2> /home/error.txt
