FROM python:3.8.16-bullseye

RUN apt-get update

WORKDIR /home/backend

ARG GIT_COMMIT_HASH
ENV GIT_COMMIT_HASH $GIT_COMMIT_HASH

## TODO: Split COPY statement for better caching
COPY ./backend .
COPY ./backend/secrets/dev_db.py ./db.py
COPY ./backend/secrets/S3_credentials.py ./S3/credentials.py

RUN pip3 install -r ./requirements.txt

CMD python ./main.py
