import styled from 'styled-components'
import React from 'react'
import { ClickableDateContainer } from './ClickableDateContainer'

export const MiddleDateRows = (firstDate: number, assignedMonth: number, eventDates: number[]) => {
  return (
    <>
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
      <ClickableDateContainer
        date={firstDate++}
        isBlurred={false}
        assignedMonth={assignedMonth}
        eventDates={eventDates}
      />
    </>
  )
}
